version: '3'

services:
  app:
    container_name: le4db_app_dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: reflex -r '(\.go$$|go\.mod)' -s go run main.go
    volumes:
      - .:/go/src/github.com/atrn0/le4db
  postgres:
    container_name: le4db_postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=le4db
      - POSTGRES_PASSWORD=password
    volumes:
    - le4db_pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
  seed:
    container_name: le4db_seed
    build:
      context: backend
      dockerfile: docker/Dockerfile
    command: go run seed.go
    volumes:
    - .:/go/src/github.com/atrn0/le4db
  psqldef:
    container_name: le4db_psqldef
    build:
      context: backend
      dockerfile: docker/sqldef/Dockerfile
    volumes:
    - psql:/schema

volumes:
  le4db_pgdata:

