version: '3'

services:
  postgres:
    container_name: le4db_postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=le4db
      - POSTGRES_PASSWORD=password
    volumes:
    - le4db_pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432

volumes:
  le4db_pgdata:

