version: '3'

services:
  app:
    container_name: le4db_app_dev
    build:
      context: backend
      dockerfile: Dockerfile
    command: reflex -r '(\.go$$|go\.mod)' -s go run main.go
    volumes:
      - .:/go/src/github.com/atrn0/le4db
    ports:
      - 8080:8080
  postgres:
    container_name: le4db_postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=le4db
      - POSTGRES_PASSWORD=pass
    volumes:
      - le4db_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  seed:
    container_name: le4db_seed
    build:
      context: backend
      dockerfile: Dockerfile
    command: go run seed.go
    volumes:
      - .:/go/src/github.com/atrn0/le4db
  swagger-ui:
    container_name: le4db-swagger-ui
    image: swaggerapi/swagger-ui:v3.20.7
    ports:
      - 8081:8080
    volumes:
      - ./openapi/spec/:/usr/share/nginx/html/spec/
    env_file:
      - openapi/swagger.env
  frontend:
    container_name: le4db-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    command: yarn start
  frontend-prod:
    container_name: le4db-frontend-prod
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    ports:
      - 3001:3000
    command: caddy run
  backend-prod:
    container_name: le4db-backend-prod
    restart: always
    build:
      context: backend
      dockerfile: prod.Dockerfile
    ports:
    - 8080:8080
    command: /le4db

volumes:
  le4db_pgdata:
