openapi: 3.0.3
info:
  title: airdnb API (for host)
  version: "1"
servers:
  - url: http://localhost:8080/v1/host
    description: host API

paths:
  /rooms:
    get:
      tags:
        - rooms
      operationId: getRooms
      description: 自分が掲載している部屋を取得
      security:
        - idToken: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRoomsRes'
    post:
      tags:
        - rooms
      operationId: postRooms
      description: 新しい部屋を掲載
      security:
        - idToken: []
      requestBody:
        description: 新しい部屋の掲載リクエスト
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRoomsReq'
      responses:
        204:
          description: NoContent
  /reservations:
    get:
# TODO: 時間でcursor
      tags:
        - reservations
      operationId: getReservations
      description: 予約一覧を取得
      security:
        - idToken: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReservationsRes'

components:
  schemas:
    GetRoomsRes:
      type: object
      required:
        - rooms
      properties:
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/Room'
    PostRoomsReq:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          example: リッツカールトン
        price:
          type: integer
          example: 300000
    GetReservationsRes:
      type: object
      required:
        - reservations
      properties:
        reservations:
          type: array
          items:
            $ref: '#/components/schemas/Reservation'
    Reservation:
      type: object
      required:
        - id
        - check_in
        - check_out
        - room_id
        - room_name
        - guest_id
        - guest_name
      properties:
        id:
          type: string
          example: lsakdjfoie
        check_in:
          type: string
          format: date-time
          example: 2006-01-02T15:04:05Z07:00
        check_out:
          type: string
          format: date-time
          example: 2006-01-02T15:04:05Z07:00
        room_id:
          type: string
          example: slafdjio
        room_name:
          type: string
          example: リッツカールトン
        guest_id:
          type: string
          example: laskjfoie
        guest_name:
          type: string
          example: きむら
    Room:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          example: laksjdfasdf
        name:
          type: string
          example: リッツカールトン
        price:
          type: integer
          example: 2000000
